name: Node.js CI

on: [pull_request]

jobs:
  fizzbuzz:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: "14.4.0"
      - run: |
          npm install
          npm test
          npm run coverage
